on: push
name: Build Angular
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Angular Github Actions
  # You may pin to the exact commit or the version.
  # uses: mayurrawte/github-angular-actions@babc38d81371a05fbe9b9b6d50d241efb96d4faf
  uses: mayurrawte/github-angular-actions@latest
